CREATE TABLE KHACH_HANG (
    MaKH VARCHAR(10) PRIMARY KEY,
    TenKH VARCHAR(50),
    DiaChi VARCHAR(100),
    DienThoai VARCHAR(15)
);

CREATE TABLE DON_DAT_HANG (
    SoDH VARCHAR(10) PRIMARY KEY,
    MaKH VARCHAR(10),
    NgayDat DATE,
    FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH)
);

CREATE TABLE SAN_PHAM (
    MaSP VARCHAR(10) PRIMARY KEY,
    TenSP VARCHAR(50),
    MoTa VARCHAR(255),
    DonViTinh VARCHAR(20),
    DonGia DECIMAL(10,2)
);

CREATE TABLE CHI_TIET_DON_HANG (
    SoDH VARCHAR(10),
    MaSP VARCHAR(10),
    SoLuong INT,
    PRIMARY KEY (SoDH, MaSP),
    FOREIGN KEY (SoDH) REFERENCES DON_DAT_HANG(SoDH),
    FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
);

CREATE TABLE PHIEU_GIAO_HANG (
    SoPGH VARCHAR(10) PRIMARY KEY,
    SoDH VARCHAR(10),
    NgayGiao DATE,
    NoiGiaoHang VARCHAR(100),
    MaNV VARCHAR(10),
    FOREIGN KEY (SoDH) REFERENCES DON_DAT_HANG(SoDH),
    FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV)
);

CREATE TABLE CHI_TIET_GIAO_HANG (
    SoPGH VARCHAR(10),
    MaSP VARCHAR(10),
    SoLuong INT,
    DonGia DECIMAL(10,2),
    ThanhTien DECIMAL(10,2),
    PRIMARY KEY (SoPGH, MaSP),
    FOREIGN KEY (SoPGH) REFERENCES PHIEU_GIAO_HANG(SoPGH),
    FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
);

CREATE TABLE NHAN_VIEN (
    MaNV VARCHAR(10) PRIMARY KEY,
    TenNV VARCHAR(50),
    DienThoai VARCHAR(15)
);